### ISSUE TITLE
memory allocation of 18253611008 bytes failed

### ISSUE THREAD

**Issue by Pourfex** [nivalis-studio/e57_to_las#1]
Hello,
Been running on Windows 10 on a 4gb e57.
Got this error after a while (5-10minutes) : 

memory allocation of 18253611008 bytes failed 

with exit status code : 

returned non-zero exit status 3221226505.

command used was : 
D:\pointcloud-converter-dev\pointcloud-converter-dev/tools/Windows/newe572las/e57-to-las.exe -p ..\..\..\pointCloudSamples\cloud.e57 -o ..\..\..\pointCloudSamples\chamarandes/tmp/cloud.las

Wondering you if have tested your tool on large point cloud and if there is an option to workaround this error.
Best regards.

**Comment by pnodet** [comment]
Hi @Pourfex
Sorry for the delay, I missed your issue, we have tested this tool on way larger point cloud with no issue.
I'll close this cause it's been quite some time but we can reopen the issue if you want.
